### ISSUE TITLE
Can I compile it with Visual Studio

### ISSUE THREAD

**Issue by yousfiSaad** [anuragsoni/restless#1]
I created a project with existing sources (using visual studio 2013)
but i have more than 100 error

Error   1   error C2875: using-declaration causes a multiple declaration of 'iterator'  restless-master\test\json.hpp   137
Error   2   error C2875: using-declaration causes a multiple declaration of 'const_iterator'    restless-master\test\json.hpp   143
Error   3   error C2875: using-declaration causes a multiple declaration of 'reverse_iterator'  restless-master\test\json.hpp   149
Error   4   error C2875: using-declaration causes a multiple declaration of 'const_reverse_iterator'    restless-master\test\json.hpp   155
Error   5   error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   382
Error   6   error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   385
Error   8   error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   402
Error   9   error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   402
Error   10  error C2143: syntax error : missing ',' before 'std::is_constructiblenlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType,V::mapped_type>::value' restless-master\test\json.hpp   402
Error   11  error C2977: 'std::enable_if' : too many template arguments restless-master\test\json.hpp   402
Error   12  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   restless-master\test\json.hpp   403
Error   13  error C2065: 'not' : undeclared identifier  restless-master\test\json.hpp   426
Error   15  error C2923: 'std::is_same' : 'nlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType>::iterator' is not a valid template type argument for parameter '_Ty2'  restless-master\test\json.hpp   426
Error   16  error C2143: syntax error : missing ',' before 'std::integral_constant<bool,false>::value'  restless-master\test\json.hpp   426
Error   17  error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   427
Error   18  error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   427
Error   19  error C2146: syntax error : missing ',' before identifier 'not' restless-master\test\json.hpp   427
Error   20  error C2065: 'not' : undeclared identifier  restless-master\test\json.hpp   427
Error   22  error C2923: 'std::is_same' : 'nlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType>::const_iterator' is not a valid template type argument for parameter '_Ty2'    restless-master\test\json.hpp   427
Error   23  error C2143: syntax error : missing ',' before 'std::integral_constant<bool,false>::value'  restless-master\test\json.hpp   427
Error   24  error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   428
Error   25  error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   428
Error   26  error C2146: syntax error : missing ',' before identifier 'not' restless-master\test\json.hpp   428
Error   27  error C2065: 'not' : undeclared identifier  restless-master\test\json.hpp   428
Error   29  error C2923: 'std::is_same' : 'nlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType>::reverse_iterator' is not a valid template type argument for parameter '_Ty2'  restless-master\test\json.hpp   428
Error   30  error C2143: syntax error : missing ',' before 'std::integral_constant<bool,false>::value'  restless-master\test\json.hpp   428
Error   31  error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   429
Error   32  error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   429
Error   33  error C2146: syntax error : missing ',' before identifier 'not' restless-master\test\json.hpp   429
Error   34  error C2065: 'not' : undeclared identifier  restless-master\test\json.hpp   429
Error   36  error C2923: 'std::is_same' : 'nlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType>::const_reverse_iterator' is not a valid template type argument for parameter '_Ty2'    restless-master\test\json.hpp   429
Error   37  error C2143: syntax error : missing ',' before 'std::integral_constant<bool,false>::value'  restless-master\test\json.hpp   429
Error   38  error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   430
Error   39  error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   430
Error   40  error C2146: syntax error : missing ',' before identifier 'not' restless-master\test\json.hpp   430
Error   41  error C2065: 'not' : undeclared identifier  restless-master\test\json.hpp   430
Error   42  error C2143: syntax error : missing ',' before 'std::is_same<V,ArrayType<nlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType>,>::iterator>::value' restless-master\test\json.hpp   430
Error   44  error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   431
Error   45  error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   431
Error   46  error C2146: syntax error : missing ',' before identifier 'not' restless-master\test\json.hpp   431
Error   47  error C2065: 'not' : undeclared identifier  restless-master\test\json.hpp   431
Error   48  error C2143: syntax error : missing ',' before 'std::is_same<V,ArrayType<nlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType>,>::const_iterator>::value'   restless-master\test\json.hpp   431
Error   50  error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   432
Error   51  error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   432
Error   52  error C2143: syntax error : missing ',' before 'std::is_constructiblenlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType,V::value_type>::value'  restless-master\test\json.hpp   432
Error   53  error C2977: 'std::enable_if' : too many template arguments restless-master\test\json.hpp   432
Error   54  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   restless-master\test\json.hpp   433
Error   55  error C2535: 'nlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType>::basic_json(const V &)' : member function already defined or declared   restless-master\test\json.hpp   434
Error   57  error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   485
Error   58  error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   485
Error   59  error C2143: syntax error : missing ',' before 'std::numeric_limits<T>::is_integer' restless-master\test\json.hpp   485
Error   60  error C2977: 'std::enable_if' : too many template arguments restless-master\test\json.hpp   485
Error   61  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   restless-master\test\json.hpp   486
Error   63  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   487
Error   64  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   502
Error   66  error C2923: 'std::is_same' : 'nlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType>::iterator' is not a valid template type argument for parameter '_Ty2'  restless-master\test\json.hpp   593
Error   67  error C2146: syntax error : missing ',' before identifier 'or'  restless-master\test\json.hpp   594
Error   68  error C2065: 'or' : undeclared identifier   restless-master\test\json.hpp   594
Error   70  error C2923: 'std::is_same' : 'nlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType>::const_iterator' is not a valid template type argument for parameter '_Ty2'    restless-master\test\json.hpp   594
Error   71  error C2143: syntax error : missing ',' before 'std::integral_constant<bool,false>::value'  restless-master\test\json.hpp   595
Error   72  error C2977: 'std::enable_if' : too many template arguments restless-master\test\json.hpp   595
Error   73  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   restless-master\test\json.hpp   596
Error   74  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   747
Error   75  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   760
Error   77  error C2061: syntax error : identifier 'value'  restless-master\test\json.hpp   761
Error   78  error C2091: function returns function  restless-master\test\json.hpp   766
Error   79  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   777
Error   80  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   836
Error   81  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   849
Error   82  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   855
Error   83  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   861
Error   84  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   867
Error   85  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   873
Error   86  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   879
Error   87  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   885
Error   88  error C3646: 'noexcept' : unknown override specifier    restless-master\test\json.hpp   891
Error   90  error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   904
Error   91  error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   904
Error   92  error C2143: syntax error : missing ',' before 'std::is_convertiblenlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType,T::mapped_type>::value'   restless-master\test\json.hpp   905
Error   93  error C2977: 'std::enable_if' : too many template arguments restless-master\test\json.hpp   905
Error   94  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   restless-master\test\json.hpp   905
Error   96  error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   941
Error   97  error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   941
Error   98  error C2146: syntax error : missing ',' before identifier 'not' restless-master\test\json.hpp   941
Error   99  error C2065: 'not' : undeclared identifier  restless-master\test\json.hpp   941
Error   100 error C2143: syntax error : missing ',' before 'std::is_samenlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType,T::value_type>::value'   restless-master\test\json.hpp   941
Error   102 error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   942
Error   103 error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   942
Error   104 error C2146: syntax error : missing ',' before identifier 'not' restless-master\test\json.hpp   942
Error   105 error C2065: 'not' : undeclared identifier  restless-master\test\json.hpp   942
Error   106 error C2143: syntax error : missing ',' before 'std::is_arithmetic<T>::value'   restless-master\test\json.hpp   942
Error   108 error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   943
Error   109 error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   943
Error   110 error C2146: syntax error : missing ',' before identifier 'not' restless-master\test\json.hpp   943
Error   111 error C2065: 'not' : undeclared identifier  restless-master\test\json.hpp   943
Error   112 error C2143: syntax error : missing ',' before 'std::is_convertiblestd::string,T::value'  restless-master\test\json.hpp   943
Error   114 error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   944
Error   115 error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   944
Error   116 error C2146: syntax error : missing ',' before identifier 'not' restless-master\test\json.hpp   944
Error   117 error C2065: 'not' : undeclared identifier  restless-master\test\json.hpp   944
Error   118 error C2143: syntax error : missing ',' before 'nlohmann::has_mapped_type<T>::value'    restless-master\test\json.hpp   945
Error   119 error C2977: 'std::enable_if' : too many template arguments restless-master\test\json.hpp   945
Error   120 error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   restless-master\test\json.hpp   945
Error   121 error C2535: 'T nlohmann::basic_json<ObjectType,ArrayType,StringType,BooleanType,NumberIntegerType,NumberFloatType,AllocatorType>::get_impl(T *) const' : member function already defined or declared   restless-master\test\json.hpp   946
Error   123 error C2146: syntax error : missing ',' before identifier 'and' restless-master\test\json.hpp   971
Error   124 error C2065: 'and' : undeclared identifier  restless-master\test\json.hpp   971
Error   125 error C2146: syntax error : missing ',' before identifier 'not' restless-master\test\json.hpp   971
Error   126 error C1003: error count exceeds 100; stopping compilation  restless-master\test\json.hpp   971

**Comment by anuragsoni** [comment]
Hi, these are all from the json.hpp that i used as a helper in the tests. The library i used doesn't work on MSVC as of this point. This is the message on their page "Unfortunately, Microsoft Visual C++ support at the moment. MSVC 2013 and MSVC 2014 have been reported not to be able to compile class". I will try and find some other means of testing without relying on the external lib. Thanks for pointing this out.

**Comment by yousfiSaad** [comment]
Thank you @anuragsoni :)

**Comment by anuragsoni** [comment]
@yousfiSaad For the time being i'd say don't include the 'test' folder in your project and you shouldn't get any errors :)

**Comment by yousfiSaad** [comment]
Hi @anuragsoni 
yes exactely, i excluded the test folder.
There is some other problems with visual studio
1. in https://github.com/anuragsoni/restless/blob/master/src/restless.hpp#L20
delete is as macro in file winnt.h, so i changed the declaration to enum class Request_Type {RTGET, RTPUT, RTPOST, RDELETE};
2. in the file https://github.com/anuragsoni/restless/blob/master/src/helpers.hpp
std::ptr_fun<int, int>(std::isspace) is ambiguous, (honestly i do not know why) i replace  std::ptr_fun by std::pointer_to_unary_function, and it works.
3. i also added some *.lib in the dependencies

I can create a pull request with those changes... is it okey ?

**Comment by anuragsoni** [comment]
1. I had the feeling that this problem shouldn't occur if i'm using scoped enums but I was re-factoring the code to to remove some duplication (public API will stay the same) so i'll add this change to that list too. 
2. This is surprising for me as well as. 
3. Were there any additional dependencies apart from libcurl? 

I am working on re-factoring the code to remove code duplication and i'll be updating the repository in a couple of days, so i'll wait for making a pull request after that. 

Thanks,
Anurag

**Comment by yousfiSaad** [comment]
ws2_32.lib
wldap32.lib

No problemo

**Comment by anuragsoni** [comment]
I will be closing the issue for now as the json library marks that it supports some versions of MSVC now. This can be opened again if you think its still not resolved. But since I don't have access to a windows machine someone else might need to take initiative with that.

Thanks.
